### PR TITLE
Update for xcb 1.1

### PR DESCRIPTION
**Pull request by wez**
The API changed quite substantially (and for the better!).
This commit is adjusting for that.

There's a wart that I hope will be tackled upstream in
https://github.com/rust-x-bindings/rust-xcb/issues/188

### CODE REVIEW

**Comment by H-M-H** [comment]
Thanks, I had a quick look and tested your changes, everything seems to be working fine. With one exception: The example now crashes once I close one of the windows. It looks like it got a little more complicated to gracefully exit.

Do you think it's worth waiting for upstream? Otherwise, I am okay with doing a release with said wart.

**Comment by wez** [comment]
I'd suggest holding for now: I'm not sure it's working 100% in wezterm and I'd like to get to the bottom of it!

**Comment by wez** [comment]
I think this is good to review/merge now!

**Comment by H-M-H** [comment]
Thanks, it's looking fine to me except for the fact that rust-xcb has no release with your required fix yet and thus this PR still points to your fork.

**Comment by H-M-H** [comment]
Merging for now, I will do a release once there is a new rust-xcb release.

**Pull request merged**
